### ISSUE TITLE
Geocluster Incompat with Wilder Wilds

### ISSUE THREAD

**Issue by LittleManDiscord** [mrsterner/Geocluster#2]
Using Geocluster and Wilder Wilds causes the game to crash on startup. Some incompatibility issues with their library mod Frozenlib maybe?

Asked the devs of Wilder Wilds and they mentioned something about Mixinextras

RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'frozenlib'!
<html>at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)<br>at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)<br>at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)<br>at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)<br>at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)<br>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)<br>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>

EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'frozenlib'
<html>at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)<br>at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)<br>... 4 more</html>

RuntimeException: Mixin transformation of net.frozenblock.lib.FrozenPreLaunch failed
<html>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)<br>at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)<br>at java.base/java.lang.Class.forName0(Native Method)<br>at java.base/java.lang.Class.forName(Class.java:467)<br>at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)<br>at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)<br>at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)<br>... 5 more</html>

NoClassDefFoundError: com/llamalad7/mixinextras/MixinExtrasBootstrap
<html>at dev.sterner.geocluster.mixin.GeoMixinPlugin.onLoad(GeoMixinPlugin.java:15)<br>at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)<br>at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:709)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)<br>at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)<br>at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)<br>... 14 more</html>

ClassNotFoundException: com.llamalad7.mixinextras.MixinExtrasBootstrap
<html>at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)<br>at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)<br>at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)<br>... 24 more</html>

**Comment by makumaku1974** [comment]
there is a mod that compats it with but it needs Extended Block Shapes.
